/**
 * Protocol callback function define here.
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.8
 * Script version: v0.1
 */

#pragma once

#include <memory>
#include <asio/awaitable.hpp>

class IPackage;
class IBasePlayer;

using AConnectionPointer = std::shared_ptr<class UConnection>;
using asio::awaitable;

namespace protocol {

	// Login

	// Appearance
	awaitable<void> C2W_AppearanceRequest(const std::shared_ptr<IBasePlayer> &plr, IPackage *pkg);

	// Chat
	awaitable<void> C2W_ChatRoomRequest(const std::shared_ptr<IBasePlayer> &plr, IPackage *pkg);
	awaitable<void> C2W_ChatToRoomRequest(const std::shared_ptr<IBasePlayer> &plr, IPackage *pkg);
	awaitable<void> Q2W_ChatResponse(IPackage *pkg);

} // protocol

#include "ProtoType.h"
#include <system/protocol/ProtocolSystem.h>

inline void LoadProtocol(UProtocolSystem *sys) {

	using namespace protocol;

	// Login

	// Appearance
	REGISTER_PROTOCOL(C2W_AppearanceRequest)

	// Chat
	REGISTER_PROTOCOL(C2W_ChatRoomRequest)
	REGISTER_PROTOCOL(C2W_ChatToRoomRequest)
	REGISTER_FROM_CROSS(Q2W_ChatResponse)

}

#include <CrossRoute.h>

inline void LoadCrossProtocol() {

	using namespace protocol;

	// Login

	// Appearance

	// Chat
	REGISTER_TO_CROSS(W2Q_ChatBroadCast)

}
