/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.8
 * Script version: v0.1
 */

#pragma once

#include <cstdint>

namespace protocol {
	enum class EProtoType : uint32_t {
		// Login
		C2W_LoginRequest = 1001,
		W2C_LoginResponse = 1002,
		W2C_ForceLogoutResponse = 1003,

		// Appearance
		C2W_AppearanceRequest = 2001,
		W2C_AppearanceResponse = 2002,

		// Chat
		C2W_ChatRoomRequest = 3001,
		W2C_ChatRoomResponse = 3002,
		C2W_ChatToRoomRequest = 3003,
		W2C_ChatToRoomResponse = 3004,
		W2C_OnChatRoomResponse = 3005,
		W2Q_ChatBroadCast = 3006,
		Q2W_ChatResponse = 3007,

		PROTO_TYPE_MAX,
	}; // EProtoType

	constexpr const char* ProtoTypeToString(const EProtoType value) {
		switch (value) {
			// Login
			case EProtoType::C2W_LoginRequest: return "C2W_LoginRequest";
			case EProtoType::W2C_LoginResponse: return "W2C_LoginResponse";
			case EProtoType::W2C_ForceLogoutResponse: return "W2C_ForceLogoutResponse";

			// Appearance
			case EProtoType::C2W_AppearanceRequest: return "C2W_AppearanceRequest";
			case EProtoType::W2C_AppearanceResponse: return "W2C_AppearanceResponse";

			// Chat
			case EProtoType::C2W_ChatRoomRequest: return "C2W_ChatRoomRequest";
			case EProtoType::W2C_ChatRoomResponse: return "W2C_ChatRoomResponse";
			case EProtoType::C2W_ChatToRoomRequest: return "C2W_ChatToRoomRequest";
			case EProtoType::W2C_ChatToRoomResponse: return "W2C_ChatToRoomResponse";
			case EProtoType::W2C_OnChatRoomResponse: return "W2C_OnChatRoomResponse";
			case EProtoType::W2Q_ChatBroadCast: return "W2Q_ChatBroadCast";
			case EProtoType::Q2W_ChatResponse: return "Q2W_ChatResponse";

			default: return "UNDEFINED";
		} // switch
	}

} // protocol