import platform
import os

VERSION = '0.1'

def generate_protobuf_define(src: str, dist: str, proto: list, include_dir: str):
    """生成协议枚举类型、回调函数声明头文件和回调注册源文件"""
    
    assert src, 'proto input path error'
    assert dist, 'proto output path error'

    print(f'-- Protobuf input path: {os.getcwd()}\\{src}')
    print(f'-- Protobuf output path: {os.getcwd()}\\{dist}')

    if not os.path.exists(dist):
        os.makedirs(dist)
        print("-- Creating proto output folder")

    proto_data = []
    proto_name_set = []

    for val in proto:
        with open(os.path.join(src, val + '.proto'), 'r', encoding='utf-8') as file:
            package = {'list': []}

            in_message = False

            is_ingore = False
            is_to_client = False

            line = file.readline()
            while line:
                if line.startswith('}') and in_message:
                    is_to_client = False
                    is_ingore = False
                    in_message = False

                line = line.strip()
                if line.startswith('package'):
                    package['package'] = line[8:-1].strip()

                if line.startswith('// @ignore'):
                    is_ingore = True

                if line.startswith('// @client'):
                    is_to_client = True

                if line.startswith('message') and not in_message:
                    in_message = True

                    
                    line = line.strip()
                    line = line[8:-1].strip()

                    
                    if line in proto_name_set:
                        raise f"{line} redefined."

                    proto_name_set.append(line)
                        
                    if is_to_client or is_ingore:
                        package['list'].append({'proto': line, 'callback': 0})
                    else:
                        package['list'].append({'proto': line, 'callback': 1})

                line = file.readline()

            proto_data.append(package)

            print(f"-- \t{file.name} have done")


    with open(os.path.join(dist, 'proto_type.h'), 'w', encoding='utf-8') as file:
        file.write(f'''/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Python version: v{platform.python_version()}
 * Script version: v{VERSION}
 */\n\n''')

        file.write('#pragma once\n\n')
        file.write('#include <cstdint>\n\n')

        file.write('namespace protocol {\n')
        file.write('\tenum class ProtoType : uint32_t {\n')

        package_index = 1
        proto_index = 1

        for package in proto_data:
            proto_index = 1
            file.write('\t\t// %s\n' % package['package'])

            for proto in package['list']:
                pkg_id = package_index * 1000 + proto_index
                file.write('\t\t%s = %d,\n' % (proto['proto'], pkg_id))

                proto_index += 1

            file.write('\n')
            package_index += 1

        file.write('\t\tPROTO_TYPE_MAX,\n')
        file.write('\t}; // ProtoType\n\n')

        file.write('\tconstexpr const char* ProtoTypeToString(const ProtoType value) {\n')
        file.write('\t\tswitch (value) {\n')

        for package in proto_data:
            file.write(f'\t\t\t// {package['package']}\n')

            for proto in package['list']:
                file.write(f'\t\t\tcase ProtoType::{proto['proto']}: return "{proto['proto']}";\n')

            file.write('\n')

        file.write('\t\t\tdefault: return "UNDEFINED";\n')
        file.write('\t\t} // switch\n')
        file.write('\t}\n\n')
    
        file.write('} // protocol')

    with open(os.path.join(dist, 'proto.def.h'), 'w', encoding='utf-8') as file:
        file.write('''/**
 * Protocol callback function define here.
 * This file is generated by Python script. Do not edit!!!
 * Python version: v%s
 * Script version: v%s
 */\n\n''' % (platform.python_version(), VERSION))

        file.write('#pragma once\n\n')
        file.write('#include <memory>\n\n\n')
        # file.write('#include <asio/awaitable.hpp>\n\n')

        file.write('class IPackage;\n')
        file.write('class IBasePlayer;\n\n')

        file.write('using ConnectionPointer = std::shared_ptr<class Connection>;\n\n')
        # file.write('using asio::awaitable;\n\n')

        file.write('namespace protocol {\n\n')

        for package in proto_data:
            file.write(f'\t// {package['package']}\n')

            for proto in package['list']:
                if proto['callback'] == 1:
                    file.write(f'\tvoid {proto['proto']}(const std::shared_ptr<IBasePlayer> &plr, IPackage *pkg);\n')

                # elif proto['callback'] == 2:
                #     file.write(f'\tawaitable<void> {proto['proto']}(IPackage *pkg);\n')

            file.write('\n')

        file.write('} // protocol\n\n')

        file.write('#include "proto_type.h"\n')
        file.write(f'#include \"{include_dir}\"\n\n')

        file.write('inline void LoadProtocol(ProtocolRoute *route) {\n\n')
        file.write('\tusing namespace protocol;\n\n')

        for package in proto_data:
            file.write(f'\t// {package['package']}\n')

            for proto in package['list']:
                if proto['callback'] == 1:
                    file.write(f'\tREGISTER_PROTOCOL({proto['proto']})\n')
                # elif proto['callback'] == 2:
                #     file.write(f'\tREGISTER_FROM_CROSS({proto['proto']})\n')

            file.write('\n')

        file.write('}\n\n')

        # file.write(f'#include <CrossRoute.h>\n\n')
        
        # file.write('inline void LoadCrossProtocol() {\n\n')
        # file.write('\tusing namespace protocol;\n\n')
        
        # for package in proto_data:
        #     file.write(f'\t// {package['package']}\n')

        #     for proto in package['list']:
        #         if proto['callback'] == 3:
        #             file.write(f'\tREGISTER_TO_CROSS({proto['proto']})\n')

        #     file.write('\n')
        
        # file.write('}\n')


