/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.9
 * Script version: v0.1
 */

#pragma once

#include <cstdint>

namespace protocol {
	enum class EProtoType : uint32_t {
		// Login
		ClientLoginRequest = 1001,
		LoginResponse = 1002,
		ForceLogoutResponse = 1003,

		// Appearance
		AppearanceRequest = 2001,
		AppearanceResponse = 2002,

		// Chat
		C2W_ChatRoomRequest = 3001,
		W2C_ChatRoomResponse = 3002,
		C2W_ChatToRoomRequest = 3003,
		W2C_ChatToRoomResponse = 3004,
		W2C_OnChatRoomResponse = 3005,
		W2Q_ChatBroadCast = 3006,
		Q2W_ChatResponse = 3007,

		PROTO_TYPE_MAX,
	}; // ProtoType

	constexpr const char* ProtoTypeToString(const EProtoType value) {
		switch (value) {
			// Login
			case EProtoType::ClientLoginRequest: return "ClientLoginRequest";
			case EProtoType::LoginResponse: return "LoginResponse";
			case EProtoType::ForceLogoutResponse: return "ForceLogoutResponse";

			// Appearance
			case EProtoType::AppearanceRequest: return "AppearanceRequest";
			case EProtoType::AppearanceResponse: return "AppearanceResponse";

			// Chat
			case EProtoType::C2W_ChatRoomRequest: return "C2W_ChatRoomRequest";
			case EProtoType::W2C_ChatRoomResponse: return "W2C_ChatRoomResponse";
			case EProtoType::C2W_ChatToRoomRequest: return "C2W_ChatToRoomRequest";
			case EProtoType::W2C_ChatToRoomResponse: return "W2C_ChatToRoomResponse";
			case EProtoType::W2C_OnChatRoomResponse: return "W2C_OnChatRoomResponse";
			case EProtoType::W2Q_ChatBroadCast: return "W2Q_ChatBroadCast";
			case EProtoType::Q2W_ChatResponse: return "Q2W_ChatResponse";

			default: return "UNDEFINED";
		} // switch
	}

} // protocol