/**
 * Protocol callback function define here.
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.9
 * Script version: v0.1
 */

#pragma once

#include <memory>


class IPackage;
class IBasePlayer;

using ConnectionPointer = std::shared_ptr<class Connection>;

namespace protocol {

	// Login

	// Appearance
	void AppearanceRequest(const std::shared_ptr<IBasePlayer> &plr, IPackage *pkg);

	// Chat

} // protocol

#include "proto_type.h"
#include "protocol_route.h"

inline void LoadProtocol(ProtocolRoute *route) {

	using namespace protocol;

	// Login

	// Appearance
	REGISTER_PROTOCOL(AppearanceRequest)

	// Chat

}

