/**
 * Protocol callback function define here.
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.8
 * Script version: v0.1
 */

#pragma once

#include <memory>


class IPackage;
class IBasePlayer;

using AConnectionPointer = std::shared_ptr<class UConnection>;
namespace protocol {

	// Login

	// Appearance
	// void C2W_AppearanceRequest(const std::shared_ptr<IBasePlayer> &plr, IPackage *pkg);

	// Chat
	// void C2W_ChatRoomRequest(const std::shared_ptr<IBasePlayer> &plr, IPackage *pkg);
	// void C2W_ChatToRoomRequest(const std::shared_ptr<IBasePlayer> &plr, IPackage *pkg);

} // protocol

#include "ProtoType.h"
#include "ProtocolRoute.h"

inline void LoadProtocol(UProtocolRoute *route) {

	using namespace protocol;

	// Login

	// Appearance
	// REGISTER_PROTOCOL(C2W_AppearanceRequest)

	// Chat
	// REGISTER_PROTOCOL(C2W_ChatRoomRequest)
	// REGISTER_PROTOCOL(C2W_ChatToRoomRequest)

}

