CREATE TABLE `appearance`
(
    `pid` BIGINT UNSIGNED NOT NULL COMMENT '玩家ID',
    `avatar` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '头像',
    `avatar_frame` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '头像框',
    `update_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间',
    PRIMARY KEY (`pid`)
) ENGINE = InnoDB CHARACTER SET = utf16 COMMENT '玩家外观';

CREATE TABLE `avatar`
(
    `pid` BIGINT UNSIGNED NOT NULL COMMENT '玩家ID',
    `index` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '索引',
    `expired_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '过期时间',
    `activated` TINYINT NOT NULL DEFAULT 0 COMMENT '是否激活',
    `in_used` TINYINT NOT NULL DEFAULT 0 COMMENT '是否正在使用',
    PRIMARY KEY (`pid`, `index`)
) ENGINE = InnoDB CHARACTER SET = utf16 COMMENT '玩家头像';

CREATE TABLE `avatar_frame`
(
    `pid` BIGINT UNSIGNED NOT NULL COMMENT '玩家ID',
    `index` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '索引',
    `expired_time` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '过期时间',
    `activated` TINYINT NOT NULL DEFAULT 0 COMMENT '是否激活',
    `in_used` TINYINT NOT NULL DEFAULT 0 COMMENT '是否正在使用',
    PRIMARY KEY (`pid`, `index`)
) ENGINE = InnoDB CHARACTER SET = utf16 COMMENT '玩家头像框';