#pragma once

/**
 * Protocol ID define here by enum class
 * This file is generated by Python script. Do not edit!!!
 * Python version: v3.12.10
 * Script version: v0.1
 */

namespace gameplay::protocol {
	enum ProtocolID {
		// greeting
		// Source File: ../protobuf/def\greeting.proto
		kGreetingRequest = 1101,
		kGreetingResponse = 1102,
		kPlayerInfoRequest = 1103,
		kPlayerInfoResponse = 1104,

		// appearance
		// Source File: ../protobuf/def\appearance.proto
		kAppearanceRequest = 1201,
		kAppearanceInfo = 1202,

	};
}
